name: PointsPlus
version: '${version}'
main: me.rockyers.pointsplus.PointsPlus
api-version: '1.20'
load: STARTUP
authors: [Rockyers, SkyGameZMC]
description: A simple, easy to use plugin to keep track of everyone's score
